### ISSUE TITLE
Default Ryu Port Version 4.15

### ISSUE THREAD

**Issue by kholisrag** [mattjhayes/nmeta#118]
For the Ryu Controller v 4.15 the default ryu port I think is 6653
it's shown in `ryu-manager --help`
and the standard port for OpenFlow in [here](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=openflow)

![screenshot from 2017-07-20 16-51-05](https://user-images.githubusercontent.com/4683704/28411675-c2193e4c-6d6b-11e7-8554-d4b49a746323.png)
![screenshot from 2017-07-20 16-50-35](https://user-images.githubusercontent.com/4683704/28411676-c2249f12-6d6b-11e7-94bc-09efd575d3d4.png)

**Comment by mattjhayes** [comment]
I'm not sure what the exactly what the issue is here?

The default OpenFlow TCP port changed a while back from 6633 to 6653. Looking at nmeta documentation, there are some places where it should be updated. I'll add that to the backlog.

Ryu (I'm running v4.13) listens on both ports:

ct1:~$ netstat -a | grep '6653\|6633'
tcp        0      0 *:6653                  *:*                     LISTEN     
tcp        0      0 *:6633                  *:*                     LISTEN     
tcp        0      0 172.16.0.3:6633         sw1.example.com:57626   ESTABLISHED
tcp        0      0 172.16.0.3:6633         172.16.0.9:38458        ESTABLISHED

**Comment by kholisrag** [comment]
maybe because it's standard just recently updated so the running port it's 6653 and 6633
